### ISSUE TITLE
New paper on LLMs detection

### ISSUE THREAD

**Issue by xunguo18** [Xianjun-Yang/Awesome_papers_on_LLMs_detection#4]
Hi, thank you for your awesome repo! 

We have a new [paper](https://arxiv.org/abs/2410.20964) to appear in NeurIPS 2024. Code is available at [this https URL](https://github.com/heyongxin233/DeTeCtive). Hope you can update this information.

Thanks!

**Comment by Xianjun-Yang** [comment]
Included! Hope you can also include our work in your reference.

**Comment by xunguo18** [comment]
@Xianjun-Yang Thanks, I will have a check!
